### ISSUE TITLE
关于 Builder 模式

### ISSUE THREAD

**Issue by ssyijiu** [mingjunli/JavaDesignPatterns#1]
请教一个问题：感觉直接在 HotDryNoodles 添加 withShallot等方法 就可以了，这样和使用Builder类有什么不一样吗？

**Comment by mingjunli** [comment]
从功能实现上withShallot放在HotDryNoodles也一样能解决问题, 但是我们必须先构造HotDryNoodles才可以调用withShallot, 这就相当于是HotDryNoodles拥有withShallot这个行为来改变自己了.

Builder模式的目的就是将复杂对象的构建独立出来处理, 便于用户根据自己的情况来定制. 从构造函数new对象, 然后调用相关方法改变成自己想要的对象, 变成了从builder生产出自己想要的对象.

**Comment by ssyijiu** [comment]
谢谢您的解答。
